### ISSUE TITLE
Cannot play on the last line

### ISSUE THREAD

**Issue by alexisjanvier** [marmelab/hex-python#9]
So, I don't know if it's a rule of the game, but it seems that we can't play on the last line of the board (line 9)

![bugHex](https://user-images.githubusercontent.com/547706/69259461-9766a600-0bbe-11ea-89e1-1f192a8cc6c9.gif)

**Comment by Chroq** [comment]
Not a rule, indeed ! :+1: 

Fixed in PR #10  [Fix the bug where a stone is put on external border of the board]
